server:
  port: 9998
spring:
  application:
    name: adminApplication
eureka:
  client:
    serviceUrl:
      defaultZone: http://123qwe:123qwe@127.0.0.1:9000/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
#server.connection-timeout: 60000
spring.boot.admin.client:
    url: http://localhost:9998
    instance:
      metadata:
        user.name: 123
        user.password: 123